### PR TITLE
CF9 Compatibility fix

### PR DESCRIPTION
**Pull request by gratzc**
There was some issues with Relax on CF9 even though it states its supported.

### CODE REVIEW

**Comment by wphampton** [comment]
+1 Solves my CF9 problems -- thanks, @gratzc.

**Comment by bdw429s** [comment]
@lmajano What needs to happen for this fix to be part of the stable build?

**Comment by lmajano** [comment]
this is in the latest build I believe

**Comment by bdw429s** [comment]
How is that possible @lmajano, I just merged it earlier today?

**Pull request merged**
